services:
    _defaults:
        autowire: true
        public: false
        autoconfigure: true

    Lle\OAuthClientBundle\Form\UserType:
        arguments: ['@Lle\OAuthClientBundle\Service\OAuthApi']
        tags: ['form.type']