login:
    path: /login
    defaults:
        _controller: Lle\OAuthClientBundle\Controller\SecurityController::login

login_check:
    path: /login_check
    defaults:
        _controller: Lle\OAuthClientBundle\Controller\SecurityController::loginCheck

logout_oauth:
    path: /logout_oauth
    defaults:
        _controller: Lle\OAuthClientBundle\Controller\SecurityController::logoutOauth

controllers:
    resource: ../../Controller/
    type: annotation
