login:
    path: /login
    defaults:
        _controller: Lle\OAuthClientBundle\Controller\SecurityController::login

login_check:
    path: /login_check
    defaults:
        _controller: Lle\OAuthClientBundle\Controller\SecurityController::loginCheck

logout_oauth:
    path: /logout_oauth
    defaults:
        _controller: Lle\OAuthClientBundle\Controller\SecurityController::logoutOauth

admin_user:
    path: /admin/user/{page}
    requirements:
        page: \d+
    defaults:
        page: 1
        _controller: Lle\OAuthClientBundle\Controller\UserAdminController::index

admin_user_edit:
    path: /admin/user/edit/{id}
    controller: Lle\OAuthClientBundle\Controller\UserAdminController::edit

admin_user_put:
    path: /admin/user/put/{id}
    controller: Lle\OAuthClientBundle\Controller\UserAdminController::put

admin_user_delete:
    path: /admin/user/delete/{id}
    controller: Lle\OAuthClientBundle\Controller\UserAdminController::delete

admin_user_form_profil:
    path: /admin/user/form/profil
    controller: Lle\OAuthClientBundle\Controller\UserAdminController::formEdit

admin_user_new:
    path: /admin/user/new
    controller: Lle\OAuthClientBundle\Controller\UserAdminController::new