services:
    lle_oauth_user_provider:
        class: Lle\OAuthClientBundle\Security\User\UserProvider
    lle_oauth_guard:
        class: Lle\OAuthClientBundle\Security\Guard\OAuthGuardAuthenticator
        arguments:
            - "KnpU\\OAuth2ClientBundle\\Client\\ClientRegistry"
            - "Symfony\\Component\\Routing\\RouterInterface"
