services:
    _defaults:
        autowire: true
        public: false
        autoconfigure: true

    lle_oauth_user_provider:
        class: Lle\OAuthClientBundle\Security\User\UserProvider

    lle_oauth_guard:
        class: Lle\OAuthClientBundle\Security\Guard\OAuthGuardAuthenticator

    Lle\OAuthClientBundle\Service\OAuthApi:
        arguments: ['@eight_points_guzzle.client.connect']

    Lle\OAuthClientBundle\Controller\UserAdminController:
        arguments: ['@Lle\OAuthClientBundle\Service\OAuthApi']
        tags: ['controller.service_arguments']

    Lle\OAuthClientBundle\Form\UserType:
        arguments: ['@Lle\OAuthClientBundle\Service\OAuthApi']
        tags: ['form.type']
