services:
    _defaults:
        autowire: true
        public: false
        autoconfigure: true

    Lle\OAuthClientBundle\Service\OAuthApi:
        arguments: [ '%lle.oauth_client.apiconnect%','%lle.oauth_client.api_user%', '%lle.oauth_client.api_password%' ]

    Lle\OAuthClientBundle\Service\OAuth2Service:
        class: Lle\OAuthClientBundle\Service\OAuth2Service

    Lle\OAuthClientBundle\Controller\SecurityController:
        arguments: [ '@parameter_bag', '@security.token_storage', '@Lle\OAuthClientBundle\Service\OAuth2Service' ]
        tags: [ 'controller.service_arguments' ]

    Lle\OAuthClientBundle\Service\ConnectApiClient:
        class: Lle\OAuthClientBundle\Service\ConnectApiClient

    Lle\OAuthClientBundle\Service\ConnectApiService:
        class: Lle\OAuthClientBundle\Service\ConnectApiService

    Lle\OAuthClientBundle\OAuth2ExceptionListener:
        tags: [ kernel.event_listener ]
