services:
    _defaults:
        autowire: true
        public: false
        autoconfigure: true

    lle_oauth_user_provider:
        class: Lle\OAuthClientBundle\Security\User\UserProvider

    lle_oauth_guard:
        class: Lle\OAuthClientBundle\Security\Guard\OAuthGuardAuthenticator

    Lle\OAuthClientBundle\Service\OAuthApi:
        arguments: ['%lle.oauth_client.domain%','%lle.oauth_client.default_user%', '%lle.oauth_client.default_password%']

    Lle\OAuthClientBundle\Controller\UserAdminController:
        arguments: ['@Lle\OAuthClientBundle\Service\OAuthApi', '@translator']
        tags: ['controller.service_arguments']


